module.exports = Object.freeze({
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_BLOCKED: 'USER_BLOCKED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
});
